For printing the random float and int value in the array.

In [1]:
import numpy as np

Print the float value

In [15]:
print(np.random.rand(3,4))

[[5.84579334e-02 3.24310455e-01 1.16640732e-02 5.67582611e-01]
 [2.36918486e-01 3.65719093e-01 4.23049404e-01 2.40678903e-01]
 [6.69968542e-04 6.17358345e-01 8.44654877e-01 9.02501411e-02]]


Print the int value.

In [10]:
# Take random value to 7.
print(np.random.randint(7, size=(4,5)))

[[2 2 5 0 5]
 [4 0 0 1 1]
 [4 5 0 2 2]
 [0 0 6 1 5]]


In [12]:
# Take random value from -1 to 7.
print(np.random.randint(-1,7 ,size=(4,5)))

[[ 2  2  0  0  6]
 [ 5 -1  2  3  4]
 [ 5  4  3  1  3]
 [ 6  6  1  3  4]]


Notice in rand method of random there is not a keyword of 'size' be careful.

Print the random number in an 'a' shape array.

In [17]:
a = np.array(((4,5),(5,6)))
print(a)

[[4 5]
 [5 6]]


In [20]:
print(a.shape)
print('\n')
print(np.random.random_sample(a.shape))

(2, 2)


[[0.10295744 0.34688023]
 [0.70368158 0.93688122]]


Repeat the array os many times.....

In [41]:
a = np.array([[[1,2,3]]])
print(np.repeat(a, 2, axis=0))

[[[1 2 3]]

 [[1 2 3]]]


In [43]:
print(np.repeat(a, 2, axis=1))

[[[1 2 3]
  [1 2 3]]]


In [48]:
print(np.repeat(a, 4, axis=1))

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]


In [49]:
print(np.repeat(a, 3, axis=2))

[[[1 1 1 2 2 2 3 3 3]]]


Print the Design :)

In [66]:
a = np.zeros((7,7), dtype=int)
b = np.ones((5,5), dtype=int)
b[2,2] = 0
a[1:-1,1:-1] = b
print(a)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 0 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


Be careful when copy the array element.

In [76]:
a = np.array(((4,5),(6,7)))
b = a
print(b)
print('\n')
b[0,1] = 0
print(a)
print('\n')
print(b)

[[4 5]
 [6 7]]


[[4 0]
 [6 7]]


[[4 0]
 [6 7]]


Notice what happen when we change the element of array 'b' then the element of array 'a' change, but this is not done.

So we use the copy() method.

In [80]:
array_a = np.array(((1,2,3,4),(5,6,7,8)))
array_b = array_a.copy()
print(b)

[[4 0]
 [6 7]]


In [82]:
array_b[0,1] = 0
print(array_b)
print('\n')
print(array_a)

[[1 0 3 4]
 [5 6 7 8]]


[[1 2 3 4]
 [5 6 7 8]]


Mathematical stuff

This link is helpful for you :->


 https://numpy.org/doc/stable/reference/routines.math.html

In [118]:
a = np.array((1,2,3,4))
print(a)

[1 2 3 4]


Add, subtract, multiply, and divide 2 to the all element of a matirx.

In [119]:
print(a+2)

[3 4 5 6]


In [120]:
print(a-2)

[-1  0  1  2]


In [121]:
print(a*2)

[2 4 6 8]


In [122]:
print(a//2)

[0 1 1 2]


Find the sin, cos, tan value of all element of all element of matrix.

In [123]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [124]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [125]:
print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


Find the degrees and radians of all element of matrix.

In [126]:
print(np.degrees(a))

[ 57.29577951 114.59155903 171.88733854 229.18311805]


In [127]:
print(np.radians(a))

[0.01745329 0.03490659 0.05235988 0.06981317]


Round off value of all the element of array.

In [128]:
a = np.random.rand(3,4)
print(a)
print('\n')
print(np.around(a))

[[0.90482576 0.37399676 0.182197   0.59542673]
 [0.2626931  0.52389126 0.36749162 0.72000969]
 [0.83578421 0.46035051 0.34686957 0.82353057]]


[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 0. 1.]]


Fix all the element of matirx 'a'.

In [131]:
print(np.fix(a))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Linear Algebra :-

https://numpy.org/doc/stable/reference/routines.linalg.html

In [225]:
a = np.ones((1,2), dtype=complex)
print(a)
print('\n')
b = np.full((2,2), 6)
print(b)
print('\n')
c = np.matmul(a,b)
print(c)

[[1.+0.j 1.+0.j]]


[[6 6]
 [6 6]]


[[12.+0.j 12.+0.j]]


Print the dot product

In [226]:
print(np.dot(a,b))

[[12.+0.j 12.+0.j]]


In [227]:
print(a.shape)

(1, 2)


In [228]:
print(b.shape)

(2, 2)


In [230]:
print(np.inner(a,b))

[[12.+0.j 12.+0.j]]


In [217]:
print(np.outer(a,b))

[[6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]]


Find the square of matrix a.

In [239]:
a = np.array(((1,2),(3,4)))
print(a)
print('\n')
print(np.linalg.matrix_power(a, 2))

[[1 2]
 [3 4]]


[[ 7 10]
 [15 22]]


Print the sum along the diagonal.

In [240]:
print(np.trace(a))

5


Notice the matirx must be square.

Thank you.