Numpy:- 
    Numpy is a numerical python library. It consist of n-dimention array and linear algerbras and others.
    Numpy is a library that is used during we are deal with data.
    Numpy is better than Python list, since it take minimun space and not checking for type. Becquse
        in an array only one type of data exists(meaning int, float).
    Numpy do all the fuctionality that are done by list.

In [213]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


we take any name like n or any other.

In [214]:
import numpy as n

In [215]:
a = n.array([1,2,3])

In [216]:
print(a)

[1 2 3]


We find the Dimention of array.

In [217]:
a.ndim

1

We find the shape of array.

In [218]:
a.shape

(3,)

we find the data type of element in the array and how may bits they contain.

In [219]:
print(a.dtype)

int32


We find the item or element size in the array in byte.

In [220]:
a.itemsize

4

Create the 2-dimention array.

In [221]:
a = n.array(((1,2,3,4),(5,6,7,8)))
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [222]:
b = n.array([[5,6,7,8],[9,10,11,12]])
print(b)

[[ 5  6  7  8]
 [ 9 10 11 12]]


Notice we are create n-dimention array with the help either this '[]' or '()'.

Repeate all the above steps.

In [223]:
a.ndim

2

In [224]:
a.shape

(2, 4)

In [225]:
print(a.dtype)

int32


In [226]:
a.size

8

In [227]:
a.nbytes

32

In [228]:
c = n.array(((1,2,3,4,5,6,7,8),(9,10,11,12,13,14,15,16)))
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


Take the element at position 1st row or 4th column.

In [229]:
c[0,3]

4

Notice it takes row as 0 and column as 3, since in python index starts with 0.

Take only one row or one column.

In [230]:
print(c[0,:])
print(c[0])

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [231]:
print(c[:,0])

[1 9]


Notice it take ' : ', since we take all row or all column.

In [232]:
print(c[0,0:-2:2])

[1 3 5]


Notice there are 1st row and 1st, 3rd, 5th, 7th column. Column go form 1st to 7th(7th column is not including) with step size 2.

Changing the existing value of array.

In [233]:
print(c)
print('\n')
c[1,6] = 6
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14  6 16]]


Changing the element of 7th column and both row.

In [234]:
print(c)
print('\n')
c[:,6] = 9
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14  6 16]]


[[ 1  2  3  4  5  6  9  8]
 [ 9 10 11 12 13 14  9 16]]


Changing the element of 7th column of both row.

In [235]:
print(c)
print('\n')
c[:,6] = [11,0]
print(c)

[[ 1  2  3  4  5  6  9  8]
 [ 9 10 11 12 13 14  9 16]]


[[ 1  2  3  4  5  6 11  8]
 [ 9 10 11 12 13 14  0 16]]


Changing the 1st row of all column.

In [236]:
print(c)
print('\n')
c[1,:] = 0
print(c)

[[ 1  2  3  4  5  6 11  8]
 [ 9 10 11 12 13 14  0 16]]


[[ 1  2  3  4  5  6 11  8]
 [ 0  0  0  0  0  0  0  0]]


In [237]:
print(c)

[[ 1  2  3  4  5  6 11  8]
 [ 0  0  0  0  0  0  0  0]]


Notice that it change the value of array permanentaly.

Three dimentional array.

In [238]:
d = n.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Grab the element.

In [239]:
print(d[1,1,0])

7


In [240]:
print(d[0,1,:])

[3 4]


In [241]:
print(d[0,:,1])

[2 4]


In [242]:
print(d[:,0,:])

[[1 2]
 [5 6]]


There are two way to print the array named as 'd'.

In [243]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [244]:
print(d[:,:,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Print the zero matrix of 1,2,3 dimention.

In [245]:
print(n.zeros((5), dtype='int32'))

[0 0 0 0 0]


In [246]:
print(n.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [247]:
print(n.zeros(((2,3,5))))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


Print the ones matrix of 3 dimention.

In [248]:
print(n.ones((((3,4,5))), dtype='int32'))

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


Print the matrix which is full form the element 5. This type of matrix is implemented in 2 ways which are:-

In [249]:
print(n.full_like(d, 5))

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


In [250]:
print(n.full(d.shape, 5))

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


Print the complex matrix.

In [254]:
print(n.full((2,2), 4, dtype='complex'))

[[4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j]]


Thank you.