Little bit more advance indexing.

In [1]:
import numpy as np

In [4]:
a = np.array(((1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15),(16,17,18,19,20),(21,22,23,24,25),(26,27,28,29,31)))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 31]]


To grab the element 11,12,16,17 from the above matrix.

In [8]:
print(a[2:4,0:2])

[[11 12]
 [16 17]]


To grab the element 2,8,14,20 from the above matrix.

In [10]:
print(a[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


To grab the element 24,25,29,31, and 4,5 from the above matrix.

In [20]:
print(a[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 31]]


In [21]:
print(a[[0,4,5],3:5])

[[ 4  5]
 [24 25]
 [29 31]]


In [29]:
print(a[[0]])

[[1 2 3 4 5]]


In [25]:
print(a[0])

[1 2 3 4 5]


Notice the above two print stuff.

To grab the 5,7,9 from the matrix given below.

In [35]:
a = np.array((1,2,3,4,5,6,7,8,9,0))
print(a)
print('\n')
print(a[[4,6,8]])

[1 2 3 4 5 6 7 8 9 0]


[5 7 9]
